name: Check RENDU.md
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ Feedback ]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 6'

jobs:
  check-title:
    runs-on: ubuntu-latest
    container: docker://docker/whalesay:latest
    steps:
      - uses: actions/checkout@v6
      - name: Check RENDU.md title
        run: |
          if grep -q '^# Rendu TD2' RENDU.md; then
            echo "Succès" | cowsay
          else
            echo "Échec" | cowsay
            exit 1
          fi
